### ISSUE TITLE
Znikający kursor myszy

### ISSUE THREAD

**Issue by koder95** [macbury/BotLogic#1]
Ciągle po jakimś czasie znika kursor myszy i jest to zapewne problem związany z nieaktualną wersją libgdx. Problem został opisany w tym wątku:
[Cursor randomly disappear when using Gdx.input.setCursorImage on desktop/Windows](https://github.com/libgdx/libgdx/issues/2839).

**Comment by macbury** [comment]
Dzięki za info, ale aktualnie projekt BotLogic nie jest już rozwijany. Oczywiście PR są mile widziane
